package com.framework.modules.shardingtest.mapper;

import com.framework.modules.shardingtest.entity.Shardingtest;
import com.framework.modules.shardingtest.entity.ShardingtestExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ShardingtestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    long countByExample(ShardingtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    int deleteByExample(ShardingtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    int insert(Shardingtest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    int insertSelective(Shardingtest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    List<Shardingtest> selectByExample(ShardingtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    Shardingtest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") Shardingtest record, @Param("example") ShardingtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    int updateByExample(@Param("record") Shardingtest record, @Param("example") ShardingtestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    int updateByPrimaryKeySelective(Shardingtest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shardingtest
     *
     * @mbg.generated Tue May 08 09:51:48 CST 2018
     */
    int updateByPrimaryKey(Shardingtest record);
}